version: "3.7"
services:

    app1_aquarium:
        build: app1_aquarium 
        restart: on-failure 
        env_file:
            - ../mailpass.env

    app2_observatory:
        build: app2_observatory 
        restart: on-failure 
        env_file:
            - ../mailpass.env

