version: "3.7"
services:
    app:
        build: app
        restart: on-failure 
        volumes:
            - .app/src:/code
        secrets:
            - mail_password
        environment:
            - MAIL_PASSWORD=/run/secrets/mail_password

secrets:
    mail_password:
        file: ./mailpass.txt
