version: "3.7"
services:
    app:
        build: app
        restart: on-failure 
        volumes:
            - .app/src:/code
        secrets:
            - MAIL_PASSWORD 
        environment:
            - MAIL_PASSWORD

secrets:
    MAIL_PASSWORD:
        external: true
