version: "3.7"
services:
    app:
        build: app
        restart: on-failure 
        env_file:
            - ../mailpass.env
#    app2:
#        build: app2
#        restart: on-failure 
#        env_file:
#            - ../mailpass.env

